/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 10:14:56 UTC 2021
 */

package org.mockito.internal.invocation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.mockito.internal.invocation.Invocation;
import org.mockito.internal.invocation.MockitoMethod;
import org.mockito.internal.invocation.realmethod.RealMethod;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVFS = true, useJEE = true) 
public class Invocation_ESTest extends Invocation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockitoMethod mockitoMethod0 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(mockitoMethod0).isVarArgs();
      Object[] objectArray0 = new Object[3];
      objectArray0[1] = null;
      objectArray0[2] = null;
      RealMethod realMethod0 = mock(RealMethod.class, new ViolatedAssumptionAnswer());
      Invocation invocation0 = new Invocation((Object) null, mockitoMethod0, objectArray0, (-54), realMethod0);
      MockitoMethod mockitoMethod1 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(mockitoMethod1).isVarArgs();
      Invocation invocation1 = new Invocation(invocation0, mockitoMethod1, objectArray0, (-54), (RealMethod) null);
      MockitoMethod mockitoMethod2 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(mockitoMethod2).isVarArgs();
      Invocation invocation2 = new Invocation(invocation1, mockitoMethod2, objectArray0, (-54), (RealMethod) null);
      MockitoMethod mockitoMethod3 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(mockitoMethod3).isVarArgs();
      Invocation invocation3 = new Invocation(invocation2, mockitoMethod3, objectArray0, (-82), (RealMethod) null);
      MockitoMethod mockitoMethod4 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(mockitoMethod4).isVarArgs();
      Invocation invocation4 = new Invocation(invocation3, mockitoMethod4, objectArray0, 0, (RealMethod) null);
      invocation4.getRawArguments();
      try { 
        invocation1.callRealMethod();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mockito.internal.invocation.Invocation", e);
      }
  }
}
