/*
 * This file was automatically generated by EvoSuite
 * Sun May 17 17:04:36 UTC 2020
 */

package org.mockito.internal.invocation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.mockito.asm.Type;
import org.mockito.internal.invocation.Invocation;
import org.mockito.internal.invocation.MockitoMethod;
import org.mockito.internal.invocation.realmethod.RealMethod;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVFS = true, useJEE = true) 
public class Invocation_ESTest extends Invocation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = new Object();
      MockitoMethod mockitoMethod0 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(mockitoMethod0).isVarArgs();
      Object[] objectArray0 = new Object[5];
      Object object1 = new Object();
      objectArray0[0] = object1;
      byte[] byteArray0 = new byte[6];
      byteArray0[0] = (byte) (-101);
      byteArray0[1] = (byte)75;
      byteArray0[2] = (byte)15;
      byteArray0[3] = (byte) (-108);
      byteArray0[5] = (byte) (-101);
      Object object2 = new Object();
      objectArray0[3] = object2;
      Integer integer0 = new Integer((byte) (-108));
      Object[] objectArray1 = new Object[5];
      objectArray1[4] = object0;
      objectArray1[2] = object0;
      objectArray1[4] = (Object) (byte) (-108);
      Type type0 = Type.INT_TYPE;
      Type type1 = Type.BOOLEAN_TYPE;
      Invocation invocation0 = new Invocation(mockitoMethod0, mockitoMethod0, objectArray1, 2845, (RealMethod) null);
      try { 
        invocation0.callRealMethod();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mockito.internal.invocation.Invocation", e);
      }
  }
}
